name: 'Terraform Destroy'

on:
  workflow_dispatch: # Allows manual trigger

env:
  TF_LOG: INFO

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    defaults:
      run:
        shell: bash
        working-directory: ./creating-airflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Step 4: Plan and Destroy resources
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve

