name: 'Terraform Apply'

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./creating-airflow

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Run a terraform plan for pull requests only
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
 
    # This upload the file from dags folder to my s3 bucket
    - name: Sync DAGs to S3
      run:  aws s3 sync ./dags/ s3://airflow-bucket-marvel/dags/ --delete
      working-directory: .
    